### ISSUE TITLE
Native component for "RCTVideoCoreView" does not exist

### ISSUE THREAD

**Issue by zhiwehu** [GuilhermeMedeiros/react-native-videocore#7]
I got this warning when I try to run the demo.

**Comment by medeeiros** [comment]
Did you add the native module into your xcode workplace?

**Comment by zhiwehu** [comment]
@GuilhermeMedeiros yes I did.
<img width="260" alt="2016-05-11 5 23 19" src="https://cloud.githubusercontent.com/assets/1313947/15176334/252c496e-179d-11e6-961a-d10121cc3953.png">

**Comment by mygu** [comment]
+1

**Comment by medeeiros** [comment]
Can you try setting the Pod dependency to: `pod 'VideoCore', '~> 0.2.0'`?
Maybe it's related with https://github.com/GuilhermeMedeiros/react-native-videocore/issues/6

**Comment by zhiwehu** [comment]
@GuilhermeMedeiros Thanks for your reply. I tried to do the pod 'VideoCore', '~> 0.2.0' and still got the same error.

**Comment by StephanieCheng** [comment]
+1

**Comment by jku-bb** [comment]
+1

**Comment by pthomsen-bb** [comment]
+1

**Comment by StephanieCheng** [comment]
Follow up: when adding the RCTVideoCore lib to the XCode project, the directory was getting copied into the project folder. The library only seems to be needed as a Group reference - the imported library should have a yellow folder (see https://developer.apple.com/library/ios/recipes/xcode_help-structure_navigator/articles/Adding_an_Existing_File_or_Folder.html). Selecting `Create groups for any added folders` fixed it for me.

**Comment by mygu** [comment]
@StephanieCheng True.Also, I copy all the files under RCTVideoCore to XCode, it's work now. Thanks for all~

**Comment by zhiwehu** [comment]
Thanks for all of your help!
